name: dynakube
namespace: dynatrace
apiUrl: https://qnk78406.live.dynatrace.com/api
metadataEnrichment:
  enabled: true
activeGate:
  capabilities:
    - routing
    - kubernetes-monitoring
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1.5Gi
